### ISSUE TITLE
Cannot find module '../build/node/ssr'

### ISSUE THREAD

**Issue by wsdo** [JasonBoy/koa-web-kit#14]

**Comment by JasonBoy** [comment]
what script do you use to start ? the single `npm run ssr` will generate the `ssr.js`, but it is integrated with other script, unless you use `npm run watch`, `npm start` separately and your `ENABLE_SSR` is true

**Comment by wsdo** [comment]
npm run ssr  然后 npm  start  ，访问3000  查看源代码没有看到 同构 的内容呢， 怎么启动能看到呢？

**Comment by JasonBoy** [comment]
直接`npm run dev:ssr`

**Comment by wsdo** [comment]
解决了，这个项目太棒了，能否 把 ant design 加入里面呢

**Comment by JasonBoy** [comment]
这个你直接install一下，import用就行了啊，这边只是相对通用的东西，用什么UI库自己选择

**Comment by wsdo** [comment]
我试试，之前搭建的，不兼容，在国外工作？

**Comment by JasonBoy** [comment]
没
