### ISSUE TITLE
exec this command npm run dev:ssr error

### ISSUE THREAD

**Issue by guozhiwei** [JasonBoy/koa-web-kit#25]
$ npm run dev:ssr

> koa-web-kit@2.8.2 dev:ssr /myhome/koa-web-kit-2.8.2
> cross-env ENABLE_HMR=0 CSS_MODULES=0 ENABLE_SSR=1 npm-run-all -p watch watch:ssr start

> koa-web-kit@2.8.2 watch /myhome/koa-web-kit-2.8.2
> webpack --watch --progress --hide-modules --config config/webpack.config.dev.js

> koa-web-kit@2.8.2 watch:ssr /myhome/koa-web-kit-2.8.2
> npm run ssr -- --watch

> koa-web-kit@2.8.2 start /myhome/koa-web-kit-2.8.2
> nodemon --trace-warnings server.js

> koa-web-kit@2.8.2 ssr /myhome/koa-web-kit-2.8.2
> webpack --progress --config config/webpack.config.ssr.js "--watch"

[nodemon] 1.18.10
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /myhome/koa-web-kit-2.8.2/api/**/* /myhome/koa-web-kit-2.8.2/config/**/* /myhome/koa-web-kit-2.8.2/build/node/**/* /myhome/koa-web-kit-2.8.2/routes/**/* /myhome/koa-web-kit-2.8.2/utils/**/* /myhome/koa-web-kit-2.8.2/services/**/* app-config.js server.js
[nodemon] starting `node --trace-warnings server.js`
Using [/myhome/koa-web-kit-2.8.2/config/app-config.js] as basic app configuration
Using [/myhome/koa-web-kit-2.8.2/config/app-config.js] as basic app configuration
Using [/myhome/koa-web-kit-2.8.2/config/app-config.js] as basic app configuration
 10% building 0/0 modules 0 active
webpack is watching the files…

(node:56855) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
 10% building 0/0 modules 0 active
webpack is watching the files…

 10% building 0/1 modules 1 active ...ctjs/ 10% building 0/1 modules 1 active .../reactjs/koa-web-kit-2.8.2    15% building 43/73 modules 30 active ...ages/School/schoolInfo/stuPlan/index.js/myhome/koa-web-kit-2.8.2/node_modules/antd/dist/antd.css:15
body {
     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
 15% building 47/73 modules 26 active ...ages/School/schoolInfo/stuPlan/index.js[nodemon] app crashed - waiting for file changes before starting...
 15% building 47/90 modules 43 active .../pages/School/schoolInfo/yishu/index.js 19% building 82/111 module 16% building 50/103 modules 53 active ....2/node_modules/redux-thunk/es/index.js 20% building 85/111 modul 19% building 81/117 modules 36 active ...modules/core-js/modules/_regexp-exec.js 20% building 91/144 modul 34% building 200/234 modules 34 active ...kit-2.8.2/node_modules/ 71% after chunk graph WebAssemblyModules 34% building 201/234 modules 33 active ...kit-2.8.2/node_modules/antd/es/index.js 87% record chunks Record 34% building 204/234 modules 30 active ...kit-2.8.2/node_modules/antd 88% content hashing JavascriptModule 35% building 215/254 modules 39 active ...ol/schoolInfo/schoolView/viewContent.jsHash: 81441c461dd449737536
Version: webpack 4.28.4
Time: 2705ms
Built at: 2019/02/20 下午5:41:32
 Asset      Size  Chunks             Chunk Names
ssr.js  2.56 MiB     ssr  [emitted]  ssr
Entrypoint ssr = ssr.js
[./build/app/manifest.json] 368 bytes {ssr} [built]
[./build/react-loadable.json] 1.55 MiB {ssr} [built]
[./src/AppRoutes.jsx] 1.52 KiB {ssr} [built]
[./src/modules/context.js] 360 bytes {ssr} [built]
[./src/pages/routes.js] 10 KiB {ssr} [built]
[./src/ssr/index.js] 5.14 KiB {ssr} [built]
[@babel/runtime/helpers/interopRequireDefault] external "@babel/runtime/helpers/interopRequireDefault" 42 bytes {ssr} [built]
[@loadable/component] external "@loadable/component" 42 bytes {ssr} [built]
[core-js/modules/web.dom.iterable] external "core-js/modules/web.dom.iterable" 42 bytes {ssr} [built]
[prop-types] external "prop-types" 42 bytes {ssr} [built]
[react] external "react" 42 bytes {ssr} [built]
[react-dom/server] external "react-dom/server" 42 bytes {ssr} [built]
[react-loadable] external "react-loadable" 42 bytes {ssr} [built]
[react-loadable/webpack] external "react-loadable/webpack" 42 bytes {ssr} [built]
[react-router-dom] external "react-router-dom" 42 bytes {ssr} [built]
    + 203 hidden modules
 36% building 218/258 modules 40 active ...-2.8.2/src/components/ziliao/index.scss[nodemon] restarting due to changes...
[nodemon] starting `node --trace-warnings server.js`
 38% building 239/282 modules 43 active ...-2.8.2/src/components/Footer/index.scssUsing [/myhome/koa-web-kit-2.8.2/config/app-config.js] as basic app configuration
 68% building 591/604 modules 13 active ...2/node_modules/zrender/lib/core/util.js/myhome/koa-web-kit-2.8.2/node_modules/antd/dist/antd.css:15
body {
     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
[nodemon] app crashed - waiting for file changes before starting...nearGradient.js
 95% emitting ManifestPlugin(node:56855) DeprecationWarning: Chunk.forEachModule: Use for(const module of chunk.modulesIterable) instead
Hash: aa624165a41dea2ef279    
Version: webpack 4.28.4
Time: 10269ms
Built at: 2019/02/20 下午5:41:39
                    Asset       Size   Chunks             Chunk Names
                  app.css    661 KiB      app  [emitted]  app
              app.css.map    814 KiB      app  [emitted]  app
                   app.js   11.3 MiB      app  [emitted]  app
               app.js.map   11.1 MiB      app  [emitted]  app
assets/static/favicon.ico   16.6 KiB           [emitted]  
   assets/static/logo.svg   2.61 KiB           [emitted]  
              favicon.ico   16.6 KiB           [emitted]  
        index-backup.html   1.16 KiB           [emitted]  
            manifest.json  368 bytes           [emitted]  
               runtime.js   6.08 KiB  runtime  [emitted]  runtime
           runtime.js.map   5.98 KiB  runtime  [emitted]  runtime
Entrypoint app = runtime.js runtime.js.map app.css app.js app.css.map app.js.map

ERROR in ./src/App.jsx
Module not found: Error: Can't resolve 'react-addons-css-transition-group' in '/myhome/koa-web-kit-2.8.2/src'
 @ ./src/App.jsx 16:60-104
 @ ./src/index.js
Hash: 40799cda9bbd9526a833                                                   
Version: webpack 4.28.4
Time: 109ms
Built at: 2019/02/20 下午5:41:40
 Asset      Size  Chunks             Chunk Names
ssr.js  2.56 MiB     ssr  [emitted]  ssr
Entrypoint ssr = ssr.js
[./build/react-loadable.json] 1.55 MiB {ssr} [built]
    + 217 hidden modules
[nodemon] restarting due to changes...
[nodemon] starting `node --trace-warnings server.js`
Using [/myhome/koa-web-kit-2.8.2/config/app-config.js] as basic app configuration
/myhome/koa-web-kit-2.8.2/node_modules/antd/dist/antd.css:15
body {
     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by JasonBoy** [comment]
你是怎么引入ant.css的，在哪里引入的

**Comment by guozhiwei** [comment]
您好，我是用下面这种方法引入的

文件：src/page/hot/hot.js
引入  import "antd/dist/antd.css"

**Comment by JasonBoy** [comment]
在 `webpack.config.ssr.js` 里面的`externals`里吧样式文件加入白名单试一下：
```
externals: [nodeExternals({
      whitelist: [/\.(sa|sc|c)ss$/],
    })],
```

**Comment by guozhiwei** [comment]
您 好，还是会报错

**Comment by guozhiwei** [comment]
您好，webpack.config.ssr.js配置为

const webpackConfig = webpackMerge(
  {},
  {
    entry: {
      ssr: utils.resolve('src/ssr/index.js'),
    },
    target: 'node',
    mode: DEV_MODE ? 'development' : 'production',
    output: {
      path: utils.resolve('build/node'),
      filename: '[name].js',
      libraryExport: 'default',
      libraryTarget: 'commonjs2',
    },
    externals: [nodeExternals({
      whitelist: [/\.(sa|sc|c)ss$/],
    })],
    resolve: {
      ...utils.getWebpackResolveConfig(),
    },
    module: {
      rules: [
        utils.getBabelLoader(true),
        ...utils.getAllStyleRelatedLoaders(
          DEV_MODE,
          false,
          false,
          undefined,
          true
        ),
        utils.getImageLoader(DEV_MODE, APP_PATH),
        utils.getMediaLoader(DEV_MODE, APP_PATH),
      ],
    },
    plugins: [
      new webpack.DefinePlugin({
        __isBrowser__: false,
        __pathPrefix__: JSON.stringify(prefix),
      }),
      new webpack.LoaderOptionsPlugin({
        debug: DEV_MODE,
        minimize: !DEV_MODE,
        options: {
          context: APP_PATH,
        },
      }),
      // new MiniCssExtractPlugin({
      //   filename: "[name].css",
      //   chunkFilename: "[id].css"
      // }),
    ],
  }
);

还是有报错，报错信息如下：

$ npm run dev:ssr

> koa-web-kit@2.8.2 dev:ssr /home/code
> cross-env ENABLE_HMR=0 CSS_MODULES=0 ENABLE_SSR=1 npm-run-all -p watch watch:ssr start


> koa-web-kit@2.8.2 watch /home/code
> webpack --watch --progress --hide-modules --config config/webpack.config.dev.js


> koa-web-kit@2.8.2 watch:ssr /home/code
> npm run ssr -- --watch


> koa-web-kit@2.8.2 start /home/code
> nodemon --trace-warnings server.js


> koa-web-kit@2.8.2 ssr /home/code
> webpack --progress --config config/webpack.config.ssr.js "--watch"

[nodemon] 1.18.10
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /home/code/api/**/* /home/code/config/**/* /home/code/build/node/**/* /home/code/routes/**/* /home/code/utils/**/* /home/code/services/**/* app-config.js server.js
[nodemon] starting `node --trace-warnings server.js`
Using [/home/code/config/app-config.js] as basic app configuration
Using [/home/code/config/app-config.js] as basic app configuration
Using [/home/code/config/app-config.js] as basic app configuration
 10% building 0/0 modules 0 active
webpack is watching the files…

(node:58140) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
 10% building 0/1 modules 1 active .../app/spa/code/pc_koa_2.8.2/src/index.js 10% building 0/0 modules 0 active
webpack is watching the files…

 11% building 9/13 modules 4 active ...@load 10% building 1/2 modules 1 active .../runtime/helpers/interopR 11% building 10/13 modules 3 active ...@loadable/component/dist/loadable.es.js 10% building 2/2 modules 0  11% building 11/13 modules 2 active ...@load 10% building 8/9 modules 1 active ...de/pc_koa_2.8.2/build/ap 11% building 14/36 modules 22 active ...spa 11% building 13/14 modules 1 active ...ool/schoolInfo/schoolHo 14% building 35/70 modules 35 active ...ages/School/schoolInfo/stuPlan/index.js 13% building 30/39 modules   21% building 93/125 modules 32 active ...l/schoolInfo/schoolHome/schoolHome.scss/home/code/node_modules/antd/dist/antd.css:15
body {
     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
[nodemon] app crashed - waiting for file changes before starting...
 
  21% building 93/147 modules 54 active ...es/School/schoolInfo/baosong/index.scss 23% building 112/166 modu 
  24% building 118/168 modules 50 active ...8.2/node_modules/object-assign/index.js 23% building 109/167 mod 
  26% building 136/174 modules 38 active ...School/schoolInfo/professional/index.js 24% building 123/182 mod 
  26% building 136/176 modules 40 active ...2/src/components/schoolInfo/schoolAd.js 24% building 124/182 mod 
  27% building 149/193 modules 44 active ...ol/schoolInfo/yuanxi/yuanxiContent.scss

**Comment by JasonBoy** [comment]
用这个branch试一下，我试了下是可以的 https://github.com/JasonBoy/koa-web-kit/tree/issue%2325-demo
<img width="426" alt="wx20190222-150611 2x" src="https://user-images.githubusercontent.com/2911620/53225568-787cc700-36b3-11e9-812c-525cc728bb2d.png">

**Comment by guozhiwei** [comment]
这个可以正常编译了，十分感谢
