### ISSUE TITLE
命令npm run deploy 如何ssr运行？

### ISSUE THREAD

**Issue by guozhiwei** [JasonBoy/koa-web-kit#27]
您好
    再问个问题，如果想要服务器渲染（ssr）的方式运行，应执行什么命令？

    我运行了npm run deploy后，查看源码还是JS进行页面渲染的。

**Comment by JasonBoy** [comment]
配置文件里`ENABLE_SSR: true`:
https://github.com/JasonBoy/koa-web-kit#application-config-and-environment-variables

**Comment by guozhiwei** [comment]
OK,感谢。👍🏻
