### ISSUE TITLE
关于路由代理修改确认

### ISSUE THREAD

**Issue by guozhiwei** [JasonBoy/koa-web-kit#28]
在使用代理时，我本地有一些运行出问题，进行了下面的修改，烦请确认：
1.在`routes/proxy.js`中，修改
  `const apiProxy = new HttpClient({ endPoint, prefix });`
为
  `const apiProxy = new HttpClient({ endPoint: endPoint, prefix: prefix });`

2.`services/HttpClient.js` 方法  `_finalizeRequestOptions`  修改如下
`_finalizeRequestOptions(options = {}) {
    let optionPrefix = options.prefix || this.options.prefix;
    
    // TODO: a path rewrite could be better
    if (isCustomAPIPrefix && optionPrefix) {
      let optionEndPoint = options.endPoint || this.options.endPoint;
      let endPointUrl = new URL(optionEndPoint);
      options.headers.host = endPointUrl.host;

      options.url = options.url.replace(new RegExp(`^${optionPrefix}`), '');

    }
    return options;
  }`

**Comment by JasonBoy** [comment]
2. 看不出改了什么，你可以发PR看一下

**Comment by guozhiwei** [comment]
第二个是因为代理 有域名/IP的变化时，未修改代理 请求头 中的Host，导致受访服务器无法绑定主机：

比如：127.0.0.1:3000/api 代理到api.example.com/api

在api.example.com中接收到的请求头host还是为127.0.0.1:3000，
实际应该更新为api.example.com

**Comment by JasonBoy** [comment]
是的，但是也不是所有的后端会在乎host, 在乎的话，可能在node层做处理了，对于你自己的项目，可以自己定义修改代码，也可以`new HttpClient(options, gotOptions)`的时候在gotOptions里传入对应的hook, 来修改header

**Comment by guozhiwei** [comment]
目前大部分服务器每台上都会部署多个Web项目运行，如配置了多个虚拟主机的，就无法定位到是哪个虚拟主机。这是HTTP的规则呀，不只是我自己项目的需求。

**Comment by JasonBoy** [comment]
你用nginx转发， 浏览器是什么，目标机器看到的就是什么，除非你修改配置文件手动修改添加header，所以上面默认浏览器过来是什么就是什么，当然你也可以自己修改呀

**Comment by guozhiwei** [comment]
ok,您说的是代理的，我描述的是反向代理的
