### ISSUE TITLE
build之后 npm run dev IE11以下 页面白屏，求解决。

### ISSUE THREAD

**Issue by blockmood** [JasonBoy/koa-web-kit#29]
大概的问题就是 es6 class 语法没有编译，导致ie11 以下无法识别。

**Comment by JasonBoy** [comment]
在`package.json`里默认如下, 你自己改成你的支持范围：
```
"browserslist": [
    "> 1%",
    "not ie 11",
    "not op_mini all"
  ]
```

**Comment by blockmood** [comment]
兼容到IE>=9 该如何配置，直接上代码吧。

**Comment by JasonBoy** [comment]
```
"browserslist": [
    "> 1%",
    "ie >= 9",
    "not op_mini all"
  ]
```
你看看index.html还有什么head要改的

**Comment by wmq0903** [comment]
"browserslist": [
    "> 1%",
    "ie >= 9",
    "not op_mini all"
 ]
这么配置IE11可以了，不过IE10和IE9报错
“Set”未定义

**Comment by wmq0903** [comment]
请问如何解决啊

**Comment by JasonBoy** [comment]
你要支持IE9， 你直接吧`babel-polyfill`在index.js引入拉到了，
https://babeljs.io/docs/en/babel-polyfill

**Comment by blockmood** [comment]
@JasonBoy  你的意思是直接在index.js 直接 require("@babel/polyfill") || import "@babel/polyfill" ?

**Comment by JasonBoy** [comment]
`import "@babel/polyfill"`

**Comment by blockmood** [comment]
@JasonBoy  我记得我昨天晚上试过，映像中是不行。

**Comment by wmq0903** [comment]
OK 我这可以了 
入口文件添加 require('babel-polyfill')  兼容到IE9了
