### ISSUE TITLE
接口代理数据，数据被截断  会是什么原因？

### ISSUE THREAD

**Issue by lee-my** [JasonBoy/koa-web-kit#31]
![Uploading WX20190326-172052@2x1111111.png…]()
以前是好使的，可以代理，但是最近突然出现接口数据被截断，返回不了数据

**Comment by lee-my** [comment]
![image](https://user-images.githubusercontent.com/10113894/54985450-cc006e80-4feb-11e9-890e-143f359ce73c.png)
像这样 返回的不是一个完整的json

**Comment by JasonBoy** [comment]
直接调接口会没么

**Comment by lee-my** [comment]
直接调接口是好的

**Comment by JasonBoy** [comment]
可能是stream被某种网络原因关了吧，你在`proxy.js`里再pipe给`PassThrough`试一下：
```
const {PassThrough} = require('stream');
//....
router.all('*', ctx => {
    ctx.body = apiProxy.proxyRequest(ctx).pipe(PassThrough());
  });
```

**Comment by lee-my** [comment]
厉害啊！！ 好了
这是什么原因啊？

**Comment by JasonBoy** [comment]
https://github.com/koajs/koa/pull/612

**Comment by lee-my** [comment]
抱歉 又出现一个问题 
返回的接口数据，在network中中文显示乱码了  页面上显示正常  

<img width="1053" alt="WX20190327-161551@2x2222222" src="https://user-images.githubusercontent.com/10113894/55060094-a2a71780-50ab-11e9-9068-977337ea8c02.png">

**Comment by lee-my** [comment]
就谷歌会出现这样 火狐是好的

**Comment by JasonBoy** [comment]
🤦‍♂️ 应该是PassThrough不会把header 回给浏览器，试试先set头，然后再pipe：
```
    const requestStream = proxy.proxyRequest(ctx);
    const pt = requestStream.pipe(PassThrough());
    await new Promise(resolve => {
      requestStream.on('response', response => {
        ctx.status = response.statusCode;
        ctx.set(response.headers);
        resolve();
      });
    });
    ctx.body = pt;
```

**Comment by lee-my** [comment]
router.all('*', async ctx => {
    const requestStream = apiProxy.proxyRequest(ctx);
    const pt = requestStream.pipe(PassThrough());
    await new Promise(resolve => {
      requestStream.on('response', response => {
        ctx.set('content-type', response.headers['content-type']);
        resolve();
      });
    });
    ctx.body = pt;
  });

这样写好了
