### ISSUE TITLE
如何解决chrome 报错问题？

### ISSUE THREAD

**Issue by fively** [JasonBoy/koa-web-kit#33]
请问，在chrome浏览器提示的错误，访问http://localhost:3000/serviceWorker.js报错，
报错内容：
The script has an unsupported MIME type ('text/html').
Failed to load resource: net::ERR_INSECURE_RESPONSE

**Comment by JasonBoy** [comment]
这是个自定义的文件？还是哪来的？你是`npm run dev`启动的么？

**Comment by fively** [comment]
是使用chrome浏览器打开的时候提示的。采用的是 npm run dev启动的。其他的浏览器我看了 没这个错误提示

**Comment by JasonBoy** [comment]
我这边console里没有的，不知道你这哪来的

**Comment by fively** [comment]
<img width="1130" alt="WechatIMG463" src="https://user-images.githubusercontent.com/37909490/55868884-ecb5f000-5bb7-11e9-83a8-515b73942f6a.png">
启动之后，chrome浏览器打开后，点击刷新按钮，就会提示

**Comment by JasonBoy** [comment]
你用隐身模式试一下会不会有

**Comment by fively** [comment]
这个就没错误的提示了。 
我是个新手，请教下，这个是什么原因？

**Comment by JasonBoy** [comment]
把缓存清掉

**Comment by fively** [comment]
好的，我再试试。
感谢！
