### ISSUE TITLE
目前遇到一个问题，就是转发的时候可能域名转发带有/

### ISSUE THREAD

**Issue by blockmood** [JasonBoy/koa-web-kit#35]
假设 http://localhost:3000/api  可能转发的时候成了  http://www.xx.com//api || http://www.xx.com/api//... ,请问这种时候问题在哪里可以排查出来？

**Comment by JasonBoy** [comment]
app-config配置里配的地址以/结尾不影响啊，只是一个baseurl，最终拼的时候会处理，要是想看实际转发出去的地址吧`PROXY_DEBUG_LEVEL:1`设为1

**Comment by blockmood** [comment]
@JasonBoy  感谢！！
