### ISSUE TITLE
Refused to execute script from 'https:///static/13-124.chunk.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled

### ISSUE THREAD

**Issue by lee-my** [JasonBoy/koa-web-kit#37]
Refused to execute script from 'https://xx.com/static/13-124.chunk.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled

动态加载页面，控制台会出现 这个问题，为什么会出现这个问题？

偶发的

**Comment by JasonBoy** [comment]
没找到这个文件，然后路由跑到index.html了

**Comment by JasonBoy** [comment]
找不到的文件现在回直接404 not found
