### ISSUE TITLE
webpack.config.node.js文件作用？

### ISSUE THREAD

**Issue by fively** [JasonBoy/koa-web-kit#38]
请问下，webpack.config.node.js的作用是将koa的代码压缩打包么？ 如何是压缩打包，那压缩打包后，是直接启动打包后的文件么？

**Comment by JasonBoy** [comment]
是的，这个吧服务端的代码打包，但是有很多细节要注意的，特别是路径问题，打包出来只有一个文件，有些要取运行时路径的，可能会出问题

**Comment by fively** [comment]
好的，谢谢
