### ISSUE TITLE
代理返回blob对象

### ISSUE THREAD

**Issue by fively** [JasonBoy/koa-web-kit#46]
您好，使用您的框架，我遇到个问题： get请求，返回的数据如果是blob对象的话，代理中会对齐进行编码，前端接受到的数据 将不是一个blob对象，这个如何解决？
![C46F95ADE405E7D21FA43E418881C19B](https://user-images.githubusercontent.com/37909490/69223509-74d08f00-0bb6-11ea-9a97-ea027150ade7.jpg)

**Comment by JasonBoy** [comment]
你的请求的response的content-type是什么？如果不是json的话，会返回给你原始fetch的response，然后你调`response.blob()`拿到的就是Blob:
```javascript
const response = await request.get('/export');
const blobData = await response.blob();
```
<img width="656" alt="WX20191120-170720@2x" src="https://user-images.githubusercontent.com/2911620/69224881-42279600-0bb8-11ea-88e6-4c125bd7bec6.png">

**Comment by fively** [comment]
我测试了下，应该不是这个问题，我用的是axios，如果不采用got代理的时候，是可以的。但是用了got代理就不行。 response的content-type 返回的是application/octet-stream;

**Comment by JasonBoy** [comment]
代理也没做什么处理，你用代理和不用在浏览器拿到的response头一样么，或者你用原生的fetch看下什么效果，或者给个完整的例子 😕

**Comment by fively** [comment]
抱歉，是我这边设置的问题，请求的时候需要加：responseType: 'blob'，另外建议got做代理的时候，encoding设置为null
